# Generated by Django 5.2.8 on 2025-11-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('competition_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('competition_edition_id', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_away_team', to='skillcorner_opendata.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_home_team', to='skillcorner_opendata.team')),
            ],
        ),
    ]
