# Generated by Django 5.2.8 on 2025-11-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillcorner_opendata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
